name: ci
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: Run tests 2021
        run: npm test 2021/
      - name: Run tests 2022
        run: npm test 2022/
